-- TheBox database schema

-- Devices table: tracks every device seen on the network
CREATE TABLE IF NOT EXISTS devices (
    id              SERIAL PRIMARY KEY,
    mac_address     VARCHAR(17) NOT NULL UNIQUE,
    ip_address      VARCHAR(45),
    hostname        VARCHAR(255),
    vendor          VARCHAR(255),
    device_type     VARCHAR(64) DEFAULT 'unknown',   -- desktop, mobile, iot, printer, …
    os_guess        VARCHAR(255),
    first_seen      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    last_seen       TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    status          VARCHAR(32)  NOT NULL DEFAULT 'new',  -- new, trusted, quarantined, blocked
    notes           TEXT,
    open_ports      JSONB DEFAULT '[]',
    extra_info      JSONB DEFAULT '{}'
);

-- IoT allow-list: FQDNs an IoT device is permitted to reach
CREATE TABLE IF NOT EXISTS iot_allowlist (
    id          SERIAL PRIMARY KEY,
    device_id   INTEGER NOT NULL REFERENCES devices(id) ON DELETE CASCADE,
    fqdn        VARCHAR(255) NOT NULL,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE(device_id, fqdn)
);

-- Honeypot events: connection attempts to the honeypot
CREATE TABLE IF NOT EXISTS honeypot_events (
    id              SERIAL PRIMARY KEY,
    src_ip          VARCHAR(45) NOT NULL,
    src_port        INTEGER,
    dst_port        INTEGER NOT NULL,
    protocol        VARCHAR(10) NOT NULL DEFAULT 'tcp',
    payload_preview TEXT,
    severity        VARCHAR(16) NOT NULL DEFAULT 'low',  -- low, medium, high, critical
    device_id       INTEGER REFERENCES devices(id),
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- DNS events: notable DNS query log
CREATE TABLE IF NOT EXISTS dns_events (
    id          SERIAL PRIMARY KEY,
    device_id   INTEGER REFERENCES devices(id),
    src_ip      VARCHAR(45) NOT NULL,
    query       VARCHAR(255) NOT NULL,
    query_type  VARCHAR(16) NOT NULL DEFAULT 'A',
    blocked     BOOLEAN NOT NULL DEFAULT FALSE,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Network scan history
CREATE TABLE IF NOT EXISTS scan_runs (
    id              SERIAL PRIMARY KEY,
    started_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    finished_at     TIMESTAMPTZ,
    network_range   VARCHAR(64) NOT NULL,
    devices_found   INTEGER NOT NULL DEFAULT 0,
    new_devices     INTEGER NOT NULL DEFAULT 0,
    status          VARCHAR(32) NOT NULL DEFAULT 'running'
);

-- Alerts generated by any service
CREATE TABLE IF NOT EXISTS alerts (
    id          SERIAL PRIMARY KEY,
    source      VARCHAR(64) NOT NULL,   -- discovery, guardian, honeypot
    level       VARCHAR(16) NOT NULL DEFAULT 'info',  -- info, warning, critical
    title       VARCHAR(255) NOT NULL,
    detail      TEXT,
    device_id   INTEGER REFERENCES devices(id),
    acknowledged BOOLEAN NOT NULL DEFAULT FALSE,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Indices for common queries
CREATE INDEX IF NOT EXISTS idx_devices_mac        ON devices(mac_address);
CREATE INDEX IF NOT EXISTS idx_devices_ip         ON devices(ip_address);
CREATE INDEX IF NOT EXISTS idx_devices_status     ON devices(status);
CREATE INDEX IF NOT EXISTS idx_honeypot_src_ip    ON honeypot_events(src_ip);
CREATE INDEX IF NOT EXISTS idx_honeypot_created   ON honeypot_events(created_at);
CREATE INDEX IF NOT EXISTS idx_alerts_level       ON alerts(level);
CREATE INDEX IF NOT EXISTS idx_alerts_created     ON alerts(created_at);
