-- TheBox database schema

-- Users table: people who own or are responsible for devices
CREATE TABLE IF NOT EXISTS users (
    id              SERIAL PRIMARY KEY,
    username        VARCHAR(64) NOT NULL UNIQUE,
    display_name    VARCHAR(255),
    email           VARCHAR(255),
    password_hash   VARCHAR(255),
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Devices table: tracks every device seen on the network
CREATE TABLE IF NOT EXISTS devices (
    id              SERIAL PRIMARY KEY,
    mac_address     VARCHAR(17) NOT NULL UNIQUE,
    ip_address      VARCHAR(45),
    ipv6_address    VARCHAR(45),
    hostname        VARCHAR(255),
    vendor          VARCHAR(255),
    device_type     VARCHAR(64) DEFAULT 'unknown',   -- desktop, mobile, iot, printer, …
    os_guess        VARCHAR(255),
    first_seen      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    last_seen       TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    status          VARCHAR(32)  NOT NULL DEFAULT 'new',  -- new, trusted, quarantined, blocked, iot
    notes           TEXT,
    open_ports      JSONB DEFAULT '[]',
    extra_info      JSONB DEFAULT '{}',
    owner_id        INTEGER REFERENCES users(id) ON DELETE SET NULL
);

-- IoT allow-list: FQDNs an IoT device is permitted to reach.
-- device_id is nullable: NULL marks a globally-shared entry (applies to all
-- IoT devices in the iot Pi-hole group); a non-NULL value ties the entry to
-- a specific device for record-keeping.
CREATE TABLE IF NOT EXISTS iot_allowlist (
    id          SERIAL PRIMARY KEY,
    device_id   INTEGER REFERENCES devices(id) ON DELETE CASCADE,
    fqdn        VARCHAR(255) NOT NULL,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE(device_id, fqdn)
);

-- Partial unique index for globally-shared entries (device_id IS NULL).
-- The UNIQUE(device_id, fqdn) constraint above allows multiple NULLs in
-- PostgreSQL, so we need a separate index to enforce uniqueness of global FQDNs.
CREATE UNIQUE INDEX IF NOT EXISTS idx_iot_allowlist_global_fqdn
    ON iot_allowlist(fqdn) WHERE device_id IS NULL;

-- IoT learning sessions: tracks the 48-hour observation window for newly
-- discovered IoT devices.  One active session per device at a time.
CREATE TABLE IF NOT EXISTS iot_learning_sessions (
    id                    SERIAL PRIMARY KEY,
    device_id             INTEGER NOT NULL REFERENCES devices(id) ON DELETE CASCADE,
    pihole_group_name     VARCHAR(64) NOT NULL,
    learning_started_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    learning_completed_at TIMESTAMPTZ,
    status                VARCHAR(32) NOT NULL DEFAULT 'active',
    UNIQUE(device_id)
);

-- Honeypot events: connection attempts to the honeypot
CREATE TABLE IF NOT EXISTS honeypot_events (
    id                SERIAL PRIMARY KEY,
    src_ip            VARCHAR(45) NOT NULL,
    src_port          INTEGER,
    dst_port          INTEGER NOT NULL,
    protocol          VARCHAR(10) NOT NULL DEFAULT 'tcp',
    payload_preview   TEXT,
    severity          VARCHAR(16) NOT NULL DEFAULT 'low',  -- low, medium, high, critical
    interaction_level VARCHAR(16) NOT NULL DEFAULT 'none',
    intent            VARCHAR(32) NOT NULL DEFAULT 'scan',
    is_sweep          BOOLEAN NOT NULL DEFAULT FALSE,
    ports_scanned     JSONB,
    device_id         INTEGER REFERENCES devices(id),
    created_at        TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- DNS events: notable DNS query log
CREATE TABLE IF NOT EXISTS dns_events (
    id          SERIAL PRIMARY KEY,
    device_id   INTEGER REFERENCES devices(id),
    src_ip      VARCHAR(45) NOT NULL,
    query       VARCHAR(255) NOT NULL,
    query_type  VARCHAR(16) NOT NULL DEFAULT 'A',
    blocked     BOOLEAN NOT NULL DEFAULT FALSE,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Network scan history
CREATE TABLE IF NOT EXISTS scan_runs (
    id              SERIAL PRIMARY KEY,
    started_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    finished_at     TIMESTAMPTZ,
    network_range   VARCHAR(64) NOT NULL,
    devices_found   INTEGER NOT NULL DEFAULT 0,
    new_devices     INTEGER NOT NULL DEFAULT 0,
    status          VARCHAR(32) NOT NULL DEFAULT 'running'
);

-- Alerts generated by any service
CREATE TABLE IF NOT EXISTS alerts (
    id          SERIAL PRIMARY KEY,
    source      VARCHAR(64) NOT NULL,   -- discovery, guardian, honeypot
    level       VARCHAR(16) NOT NULL DEFAULT 'info',  -- info, warning, critical
    title       VARCHAR(255) NOT NULL,
    detail      TEXT,
    device_id   INTEGER REFERENCES devices(id),
    acknowledged BOOLEAN NOT NULL DEFAULT FALSE,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Indices for common queries
CREATE INDEX IF NOT EXISTS idx_devices_mac        ON devices(mac_address);
CREATE INDEX IF NOT EXISTS idx_devices_ip         ON devices(ip_address);
CREATE INDEX IF NOT EXISTS idx_devices_ipv6       ON devices(ipv6_address);
CREATE INDEX IF NOT EXISTS idx_devices_status     ON devices(status);
CREATE INDEX IF NOT EXISTS idx_devices_owner      ON devices(owner_id);
CREATE INDEX IF NOT EXISTS idx_honeypot_src_ip    ON honeypot_events(src_ip);
CREATE INDEX IF NOT EXISTS idx_honeypot_created   ON honeypot_events(created_at);
CREATE INDEX IF NOT EXISTS idx_alerts_level       ON alerts(level);
CREATE INDEX IF NOT EXISTS idx_alerts_created     ON alerts(created_at);

-- Groups table: named groups that map to Pi-hole groups for DNS policy management
CREATE TABLE IF NOT EXISTS groups (
    id                SERIAL PRIMARY KEY,
    name              VARCHAR(64) NOT NULL UNIQUE,
    description       TEXT,
    pihole_group_name VARCHAR(64),   -- name of the corresponding Pi-hole group
    created_at        TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at        TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- User-group memberships: users can belong to multiple groups
CREATE TABLE IF NOT EXISTS user_groups (
    user_id   INTEGER NOT NULL REFERENCES users(id)  ON DELETE CASCADE,
    group_id  INTEGER NOT NULL REFERENCES groups(id) ON DELETE CASCADE,
    PRIMARY KEY (user_id, group_id)
);

-- Device-group memberships: devices can belong to multiple groups
CREATE TABLE IF NOT EXISTS device_groups (
    device_id INTEGER NOT NULL REFERENCES devices(id) ON DELETE CASCADE,
    group_id  INTEGER NOT NULL REFERENCES groups(id)  ON DELETE CASCADE,
    PRIMARY KEY (device_id, group_id)
);

CREATE INDEX IF NOT EXISTS idx_user_groups_group    ON user_groups(group_id);
CREATE INDEX IF NOT EXISTS idx_device_groups_group  ON device_groups(group_id);

-- Redirector events: actions taken by the redirector service
CREATE TABLE IF NOT EXISTS redirect_events (
    id          SERIAL PRIMARY KEY,
    action      VARCHAR(64)  NOT NULL,   -- quarantine_start, quarantine_stop, dns_redirect, …
    target_ip   VARCHAR(45)  NOT NULL,
    target_mac  VARCHAR(17),
    mode        VARCHAR(64)  NOT NULL,   -- arp_spoof, redirect_dns, dhcp_advertise, …
    detail      TEXT,
    device_id   INTEGER REFERENCES devices(id),
    created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_redirect_target_ip  ON redirect_events(target_ip);
CREATE INDEX IF NOT EXISTS idx_redirect_created    ON redirect_events(created_at);

-- Runtime configuration settings
CREATE TABLE IF NOT EXISTS settings (
    key         VARCHAR(64)  NOT NULL PRIMARY KEY,
    value       TEXT         NOT NULL,
    description TEXT,
    category    VARCHAR(32)  NOT NULL DEFAULT 'general',
    updated_at  TIMESTAMPTZ  NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_settings_category ON settings(category);

-- Migration tracking — records which versioned migrations have been applied.
-- Populated here so that fresh installs (where Docker runs this file
-- automatically) are already in sync when upgrade.sh runs later.
CREATE TABLE IF NOT EXISTS schema_migrations (
    version     VARCHAR(16) NOT NULL PRIMARY KEY,
    applied_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Mark all migrations as applied on a fresh install since this file
-- includes the complete up-to-date schema.
INSERT INTO schema_migrations (version) VALUES ('0001') ON CONFLICT (version) DO NOTHING;
INSERT INTO schema_migrations (version) VALUES ('0002') ON CONFLICT (version) DO NOTHING;
INSERT INTO schema_migrations (version) VALUES ('0003') ON CONFLICT (version) DO NOTHING;
INSERT INTO schema_migrations (version) VALUES ('0004') ON CONFLICT (version) DO NOTHING;
